// Tool Registry - Central registry for all browser tools
import type { ToolMetadata } from '../types';

export const tools: ToolMetadata[] = [
  // === IMAGE TOOLS ===
  {
    id: 'image-compressor',
    slug: 'bild-komprimieren',
    name: 'Bild Komprimieren',
    shortName: 'Komprimieren',
    description: 'Komprimiere Bilder schnell und effizient direkt im Browser. Reduziere die Dateigröße ohne sichtbaren Qualitätsverlust. Unterstützt JPEG, PNG, WebP und mehr.',
    shortDescription: 'Reduziere Bildgröße ohne Qualitätsverlust',
    category: 'image',
    keywords: ['bild komprimieren', 'image compress', 'bilder verkleinern', 'jpg komprimieren', 'png komprimieren', 'webp', 'dateigröße reduzieren'],
    icon: 'Compress',
    acceptsFiles: ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
    outputsFiles: ['image/jpeg', 'image/png', 'image/webp'],
    features: [
      'Qualitätseinstellung von 0-100%',
      'Automatische Format-Konvertierung',
      'Batch-Verarbeitung mehrerer Bilder',
      'Live-Vorschau des Ergebnisses',
      'Download aller Bilder als ZIP',
    ],
    faq: [
      { question: 'Werden meine Bilder auf einen Server hochgeladen?', answer: 'Nein, alle Verarbeitung erfolgt lokal in deinem Browser. Deine Bilder verlassen niemals dein Gerät.' },
      { question: 'Welche Bildformate werden unterstützt?', answer: 'JPEG, PNG, WebP und GIF werden vollständig unterstützt.' },
      { question: 'Gibt es eine Größenbeschränkung?', answer: 'Theoretisch nicht, aber sehr große Bilder können je nach Gerätleistung länger dauern.' },
    ],
    howTo: [
      'Ziehe Bilder per Drag & Drop oder klicke zum Hochladen',
      'Wähle die gewünschte Qualität und das Ausgabeformat',
      'Klicke auf "Komprimieren" und warte auf die Verarbeitung',
      'Lade die komprimierten Bilder herunter',
    ],
    relatedTools: ['image-resizer', 'image-converter', 'image-cropper'],
    isPopular: true,
  },
  {
    id: 'image-resizer',
    slug: 'bild-groesse-aendern',
    name: 'Bildgröße Ändern',
    shortName: 'Größe Ändern',
    description: 'Ändere die Abmessungen von Bildern schnell und präzise. Skaliere auf bestimmte Pixelmaße oder prozentual. Ideal für Web, Social Media und Druck.',
    shortDescription: 'Skaliere Bilder auf beliebige Größe',
    category: 'image',
    keywords: ['bild verkleinern', 'bild vergrößern', 'resize image', 'bild skalieren', 'auflösung ändern', 'pixel ändern'],
    icon: 'Maximize2',
    acceptsFiles: ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/bmp'],
    outputsFiles: ['image/jpeg', 'image/png', 'image/webp'],
    features: [
      'Pixel-genauer Größeinstellung',
      'Prozentuale Skalierung',
      'Seitenverhältnis beibehalten',
      'Batch-Verarbeitung',
      'Vorschau vor dem Export',
    ],
    faq: [
      { question: 'Kann ich das Seitenverhältnis beibehalten?', answer: 'Ja, aktiviere die Option "Seitenverhältnis beibehalten" für verzerrungsfreie Skalierung.' },
    ],
    howTo: [
      'Lade dein Bild hoch',
      'Gib die gewünschte Breite und/oder Höhe ein',
      'Wähle ob das Seitenverhältnis beibehalten werden soll',
      'Exportiere das skalierte Bild',
    ],
    relatedTools: ['image-compressor', 'image-cropper', 'image-converter'],
    isPopular: true,
  },
  {
    id: 'image-converter',
    slug: 'bild-konvertieren',
    name: 'Bild Konvertieren',
    shortName: 'Konvertieren',
    description: 'Konvertiere Bilder zwischen verschiedenen Formaten. Unterstützt JPEG, PNG, WebP, GIF, BMP und mehr. Schnell und ohne Qualitätsverlust.',
    shortDescription: 'Wandle Bilder in andere Formate um',
    category: 'image',
    keywords: ['bild konvertieren', 'image converter', 'jpg zu png', 'png zu webp', 'format ändern', 'bildformat'],
    icon: 'RefreshCw',
    acceptsFiles: ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/bmp', 'image/tiff'],
    outputsFiles: ['image/jpeg', 'image/png', 'image/webp'],
    features: [
      'Multi-Format Unterstützung',
      'Batch-Konvertierung',
      'Qualitätseinstellungen pro Format',
      'Schnelle Verarbeitung',
    ],
    faq: [
      { question: 'Welche Formate werden unterstützt?', answer: 'Eingabe: JPEG, PNG, WebP, GIF, BMP, TIFF. Ausgabe: JPEG, PNG, WebP.' },
    ],
    howTo: [
      'Lade Bilder hoch',
      'Wähle das Ausgabeformat',
      'Passe ggf. die Qualität an',
      'Exportiere die konvertierten Bilder',
    ],
    relatedTools: ['image-compressor', 'image-resizer'],
  },
  {
    id: 'image-cropper',
    slug: 'bild-zuschneiden',
    name: 'Bild Zuschneiden',
    shortName: 'Zuschneiden',
    description: 'Schneide Bilder präzise zu. Wähle Bereiche visuell oder gib exakte Maße ein. Ideal für Profilebilder, Thumbnails und Social Media.',
    shortDescription: 'Schneide Bilder präzise zu',
    category: 'image',
    keywords: ['bild zuschneiden', 'crop image', 'ausschnitt', 'profilbild', 'thumbnail', 'bild bearbeiten'],
    icon: 'Crop',
    acceptsFiles: ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
    outputsFiles: ['image/jpeg', 'image/png', 'image/webp'],
    features: [
      'Visuelle Auswahl des Bereichs',
      'Vorgegebene Aspect-Ratios',
      'Freie Formate',
      'Zoom-Funktion',
      'Rückgängig machen',
    ],
    faq: [
      { question: 'Kann ich vorgegebene Größen verwenden?', answer: 'Ja, wähle aus gängigen Aspect-Ratios wie 1:1, 16:9, 4:3 oder gib eigene Maße ein.' },
    ],
    howTo: [
      'Lade ein Bild hoch',
      'Wähle den gewünschten Bereich',
      'Passe die Größe an',
      'Exportiere den Ausschnitt',
    ],
    relatedTools: ['image-resizer', 'image-compressor'],
  },

  // === PDF TOOLS ===
  {
    id: 'pdf-merge',
    slug: 'pdf-zusammenfuegen',
    name: 'PDF Zusammenfügen',
    shortName: 'Zusammenfügen',
    description: 'Füge mehrere PDF-Dateien zu einem Dokument zusammen. Einfach per Drag & Drop anordnen und exportieren. Schnell und sicher.',
    shortDescription: 'Verbinde mehrere PDFs zu einer Datei',
    category: 'pdf',
    keywords: ['pdf zusammenfügen', 'merge pdf', 'pdf verbinden', 'pdf kombinieren', 'dokumente zusammenfassen'],
    icon: 'FileStack',
    acceptsFiles: ['application/pdf'],
    outputsFiles: ['application/pdf'],
    features: [
      'Drag & Drop Sortierung',
      'Vorschau jeder Seite',
      'Unbegrenzte Dateien',
      'Schnelle Verarbeitung',
    ],
    faq: [
      { question: 'Gibt es ein Limit für die Anzahl der PDFs?', answer: 'Nein, du kannst beliebig viele PDFs zusammenfügen.' },
      { question: 'Bleibt die Qualität erhalten?', answer: 'Ja, alle Inhalte werden originalgetreu übernommen.' },
    ],
    howTo: [
      'Lade mehrere PDFs hoch',
      'Ordne sie per Drag & Drop',
      'Klicke auf "Zusammenfügen"',
      'Lade die kombinierte PDF herunter',
    ],
    relatedTools: ['pdf-split', 'pdf-compress'],
    isPopular: true,
  },
  {
    id: 'pdf-split',
    slug: 'pdf-teilen',
    name: 'PDF Teilen',
    shortName: 'Teilen',
    description: 'Teile PDFs in einzelne Seiten oder Abschnitte. Wähle bestimmte Seiten aus oder extrahiere Seitenbereiche.',
    shortDescription: 'Teile PDFs in einzelne Seiten',
    category: 'pdf',
    keywords: ['pdf teilen', 'split pdf', 'pdf trennen', 'seiten extrahieren', 'pdf aufteilen'],
    icon: 'Scissors',
    acceptsFiles: ['application/pdf'],
    outputsFiles: ['application/pdf'],
    features: [
      'Einzelseiten extrahieren',
      'Seitenbereiche wählen',
      'Batch-Export',
      'Vorschau aller Seiten',
    ],
    faq: [
      { question: 'Kann ich bestimmte Seiten auswählen?', answer: 'Ja, du kannst einzelne Seiten oder Bereiche (z.B. 1-5, 8, 10-12) auswählen.' },
    ],
    howTo: [
      'Lade eine PDF hoch',
      'Wähle die gewünschten Seiten',
      'Klicke auf "Teilen"',
      'Lade die einzelnen PDFs herunter',
    ],
    relatedTools: ['pdf-merge', 'pdf-compress'],
  },
  {
    id: 'pdf-compress',
    slug: 'pdf-komprimieren',
    name: 'PDF Komprimieren',
    shortName: 'Komprimieren',
    description: 'Reduziere die Größe von PDF-Dateien ohne Qualitätsverlust. Ideal für E-Mail-Anhänge und schnelles Laden im Web.',
    shortDescription: 'Verkleinere PDF-Dateien',
    category: 'pdf',
    keywords: ['pdf komprimieren', 'compress pdf', 'pdf verkleinern', 'pdf verkleinern', 'dateigröße reduzieren'],
    icon: 'FileDown',
    acceptsFiles: ['application/pdf'],
    outputsFiles: ['application/pdf'],
    features: [
      'Qualitätsstufen wählbar',
      'Bilder in PDFs optimieren',
      'Schriftarten einbetten',
      'Vorschau der Größe',
    ],
    faq: [
      { question: 'Wie stark wird die PDF verkleinert?', answer: 'Je nach Inhalt können Reduktionen von 50-90% erreicht werden.' },
    ],
    howTo: [
      'Lade eine PDF hoch',
      'Wähle die Komprimierungsstärke',
      'Starte die Komprimierung',
      'Lade die optimierte PDF herunter',
    ],
    relatedTools: ['pdf-merge', 'image-to-pdf'],
    isNew: true,
  },
  {
    id: 'image-to-pdf',
    slug: 'bild-zu-pdf',
    name: 'Bild zu PDF',
    shortName: 'Bild → PDF',
    description: 'Wandle Bilder in PDF-Dokumente um. Mehrere Bilder können als mehrseitige PDF exportiert werden.',
    shortDescription: 'Erstelle PDFs aus Bildern',
    category: 'pdf',
    keywords: ['bild zu pdf', 'image to pdf', 'bilder in pdf', 'jpg zu pdf', 'png zu pdf', 'bilder als pdf speichern'],
    icon: 'FileImage',
    acceptsFiles: ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
    outputsFiles: ['application/pdf'],
    features: [
      'Mehrere Bilder pro PDF',
      'Seitenreihenfolge anpassen',
      'Seitengröße wählen',
      'A4, Letter, Custom',
    ],
    faq: [
      { question: 'Kann ich mehrere Bilder in eine PDF packen?', answer: 'Ja, jedes Bild wird zu einer Seite in der PDF.' },
    ],
    howTo: [
      'Lade Bilder hoch',
      'Ordne die Reihenfolge',
      'Wähle das Seitenformat',
      'Exportiere als PDF',
    ],
    relatedTools: ['pdf-merge', 'image-converter'],
  },

  // === TEXT TOOLS ===
  {
    id: 'text-counter',
    slug: 'text-zaehlen',
    name: 'Wörter & Zeichen Zählen',
    shortName: 'Zählen',
    description: 'Zähle Wörter, Zeichen, Sätze und Absätze in deinem Text. Perfekt für Autoren, Studenten und Content-Creator.',
    shortDescription: 'Analysiere Textstatistiken',
    category: 'text',
    keywords: ['wörter zählen', 'zeichen zählen', 'word count', 'text analysieren', 'text statistik', 'satz zählen'],
    icon: 'Hash',
    acceptsFiles: ['text/plain', 'text/html', 'text/markdown'],
    outputsFiles: [],
    features: [
      'Wörter zählen',
      'Zeichen mit/ohne Leerzeichen',
      'Sätze und Absätze',
      'Lesezeit schätzen',
      'Keyword-Häufigkeit',
    ],
    faq: [
      { question: 'Werden auch Leerzeichen gezählt?', answer: 'Ja, du siehst sowohl Zeichen mit als auch ohne Leerzeichen.' },
    ],
    howTo: [
      'Füge Text ein oder lade eine Datei hoch',
      'Sieh dir die Statistiken an',
      'Exportiere ggf. als Report',
    ],
    relatedTools: ['text-transform', 'text-diff'],
    isPopular: true,
  },
  {
    id: 'text-transform',
    slug: 'text-transformieren',
    name: 'Text Transformieren',
    shortName: 'Transformieren',
    description: 'Wandle Text in Großbuchstaben, Kleinbuchstaben, Title Case und mehr um. Vielseitige Text-Transformation.',
    shortDescription: 'Ändere Text-Groß-/Kleinschreibung',
    category: 'text',
    keywords: ['text transformieren', 'uppercase', 'lowercase', 'großbuchstaben', 'kleinbuchstaben', 'text formatieren'],
    icon: 'CaseSensitive',
    acceptsFiles: ['text/plain'],
    outputsFiles: ['text/plain'],
    features: [
      'GROSSBUCHSTABEN',
      'kleinbuchstaben',
      'Title Case',
      'Sentence case',
      'tOGGLE cASE',
      'camelCase / snake_case',
    ],
    faq: [
      { question: 'Kann ich mehrere Transformationen kombinieren?', answer: 'Ja, wende verschiedene Transformationen nacheinander an.' },
    ],
    howTo: [
      'Füge Text ein',
      'Wähle die Transformation',
      'Kopiere das Ergebnis',
    ],
    relatedTools: ['text-counter', 'text-cleaner'],
  },
  {
    id: 'text-diff',
    slug: 'text-vergleichen',
    name: 'Text Vergleichen',
    shortName: 'Vergleichen',
    description: 'Vergleiche zwei Texte und finde Unterschiede. Perfekt für Code-Reviews, Dokumentenvergleich und Änderungsverfolgung.',
    shortDescription: 'Finde Unterschiede zwischen Texten',
    category: 'text',
    keywords: ['text vergleichen', 'diff', 'text difference', 'änderungen finden', 'vergleich', 'unterschiede'],
    icon: 'Diff',
    acceptsFiles: ['text/plain', 'text/html', 'application/json'],
    outputsFiles: ['text/html'],
    features: [
      'Side-by-Side Vergleich',
      'Hervorhebung der Änderungen',
      'Zeilenweiser Vergleich',
      'Export als HTML',
    ],
    faq: [
      { question: 'Wie werden Änderungen markiert?', answer: 'Gelöschter Text wird rot, neuer Text grün hervorgehoben.' },
    ],
    howTo: [
      'Füge Text A ein',
      'Füge Text B ein',
      'Vergleiche und analysiere',
    ],
    relatedTools: ['json-diff', 'text-transform'],
  },

  // === DEVELOPER TOOLS ===
  {
    id: 'json-formatter',
    slug: 'json-formatieren',
    name: 'JSON Formatieren',
    shortName: 'JSON Format',
    description: 'Formatiere und validiere JSON-Daten. Verschönere unleserliches JSON mit Einrückungen und Syntax-Highlighting.',
    shortDescription: 'Verschönere und validiere JSON',
    category: 'developer',
    keywords: ['json formatieren', 'json formatter', 'json beautify', 'json pretty', 'json validieren', 'json editor'],
    icon: 'Braces',
    acceptsFiles: ['application/json'],
    outputsFiles: ['application/json'],
    features: [
      'Automatische Formatierung',
      'Syntax-Highlighting',
      'Validierung mit Fehlermeldungen',
      'Minifizierung',
      'JSON Path Abfragen',
    ],
    faq: [
      { question: 'Was ist JSON Minifizierung?', answer: 'Entfernt alle Leerzeichen und Zeilenumbrüche für kleinere Dateigröße.' },
    ],
    howTo: [
      'Füge JSON ein oder lade eine Datei',
      'Klicke auf "Formatieren"',
      'Kopiere oder speichere das Ergebnis',
    ],
    relatedTools: ['json-to-csv', 'xml-formatter'],
    isPopular: true,
  },
  {
    id: 'json-to-csv',
    slug: 'json-zu-csv',
    name: 'JSON zu CSV',
    shortName: 'JSON → CSV',
    description: 'Konvertiere JSON-Daten in CSV-Tabellen. Ideal für Datenexport und Tabellenkalkulation.',
    shortDescription: 'Wandle JSON in CSV um',
    category: 'developer',
    keywords: ['json zu csv', 'json to csv', 'json converter', 'daten exportieren', 'tabelle'],
    icon: 'Table',
    acceptsFiles: ['application/json'],
    outputsFiles: ['text/csv'],
    features: [
      'Automatische Spaltenerkennung',
      'Nested JSON Support',
      'Delimiter wählbar',
      'Header-Zeile optional',
    ],
    faq: [
      { question: 'Kann ich verschachteltes JSON konvertieren?', answer: 'Ja, nested Objects werden automatisch flachgeklopft.' },
    ],
    howTo: [
      'Lade JSON hoch',
      'Prüfe die Vorschau',
      'Exportiere als CSV',
    ],
    relatedTools: ['json-formatter', 'csv-to-json'],
  },
  {
    id: 'csv-to-json',
    slug: 'csv-zu-json',
    name: 'CSV zu JSON',
    shortName: 'CSV → JSON',
    description: 'Konvertiere CSV-Dateien in JSON-Format. Schnell und mit Vorschaufunktion.',
    shortDescription: 'Wandle CSV in JSON um',
    category: 'developer',
    keywords: ['csv zu json', 'csv to json', 'csv converter', 'daten importieren'],
    icon: 'FileJson',
    acceptsFiles: ['text/csv', 'text/tab-separated-values'],
    outputsFiles: ['application/json'],
    features: [
      'Auto-Delimiter Erkennung',
      'Array oder Object Output',
      'Typ-Inferenz',
      'Pretty Print Option',
    ],
    faq: [
      { question: 'Welche Delimiter werden erkannt?', answer: 'Komma, Semikolon, Tab und Pipe werden automatisch erkannt.' },
    ],
    howTo: [
      'Lade CSV hoch',
      'Wähle das Ausgabeformat',
      'Exportiere als JSON',
    ],
    relatedTools: ['json-to-csv', 'json-formatter'],
  },
  {
    id: 'base64-encoder',
    slug: 'base64-kodieren',
    name: 'Base64 Encoder/Decoder',
    shortName: 'Base64',
    description: 'Kodiere und dekodiere Text oder Dateien in Base64. Unterstützt Text, Bilder und beliebige Binärdateien.',
    shortDescription: 'Kodiere/Dekodiere Base64',
    category: 'developer',
    keywords: ['base64', 'encoder', 'decoder', 'base64 kodieren', 'base64 dekodieren', 'encode', 'decode'],
    icon: 'Binary',
    acceptsFiles: ['*/*'],
    outputsFiles: ['text/plain', 'application/octet-stream'],
    features: [
      'Text zu Base64',
      'Base64 zu Text',
      'Datei zu Base64',
      'Base64 zu Datei',
      'URL-Safe Encoding',
    ],
    faq: [
      { question: 'Was ist Base64?', answer: 'Base64 ist ein Verfahren zur Kodierung von Binärdaten in ASCII-Zeichen.' },
    ],
    howTo: [
      'Füge Text ein oder lade eine Datei',
      'Wähle Kodieren oder Dekodieren',
      'Kopiere oder speichere das Ergebnis',
    ],
    relatedTools: ['url-encoder', 'hash-generator'],
    isPopular: true,
  },
  {
    id: 'url-encoder',
    slug: 'url-kodieren',
    name: 'URL Encoder/Decoder',
    shortName: 'URL',
    description: 'Kodiere und dekodiere URLs und URL-Komponenten. Handles Sonderzeichen und Unicode.',
    shortDescription: 'Kodiere/Dekodiere URLs',
    category: 'developer',
    keywords: ['url encoder', 'url decoder', 'urlencode', 'urldecode', 'uri encoding', 'prozentkodierung'],
    icon: 'Link',
    acceptsFiles: ['text/plain'],
    outputsFiles: ['text/plain'],
    features: [
      'Komplette URL Encoding',
      'Komponenten-Encoding',
      'Unicode Support',
      'Query String Parsing',
    ],
    faq: [
      { question: 'Wann brauche ich URL-Encoding?', answer: 'Für URLs mit Sonderzeichen, Leerzeichen oder nicht-ASCII-Zeichen.' },
    ],
    howTo: [
      'Füge URL oder Text ein',
      'Wähle Kodieren oder Dekodieren',
      'Kopiere das Ergebnis',
    ],
    relatedTools: ['base64-encoder', 'html-entities'],
  },
  {
    id: 'hash-generator',
    slug: 'hash-generieren',
    name: 'Hash Generator',
    shortName: 'Hash',
    description: 'Generiere Hash-Werte für Text und Dateien. Unterstützt MD5, SHA-1, SHA-256, SHA-512 und mehr.',
    shortDescription: 'Erstelle kryptografische Hashes',
    category: 'security',
    keywords: ['hash generator', 'md5', 'sha256', 'sha1', 'checksum', 'hash berechnen', 'prüfsumme'],
    icon: 'Key',
    acceptsFiles: ['*/*'],
    outputsFiles: ['text/plain'],
    features: [
      'MD5',
      'SHA-1',
      'SHA-256',
      'SHA-512',
      'Datei-Hash',
      'Text-Hash',
    ],
    faq: [
      { question: 'Wofür brauche ich Hashes?', answer: 'Für Datei-Integritätsprüfung, Passwort-Hashing oder digitale Signaturen.' },
    ],
    howTo: [
      'Füge Text ein oder lade eine Datei',
      'Wähle den Hash-Algorithmus',
      'Kopiere den Hash-Wert',
    ],
    relatedTools: ['password-generator', 'base64-encoder'],
    isPopular: true,
  },
  {
    id: 'password-generator',
    slug: 'passwort-generieren',
    name: 'Passwort Generator',
    shortName: 'Passwort',
    description: 'Generiere sichere, zufällige Passwörter. Konfiguriere Länge, Zeichen und Stärke.',
    shortDescription: 'Erstelle sichere Passwörter',
    category: 'security',
    keywords: ['passwort generator', 'password generator', 'sicheres passwort', 'passwort erstellen', 'random password'],
    icon: 'Lock',
    acceptsFiles: [],
    outputsFiles: ['text/plain'],
    features: [
      'Konfigurierbare Länge',
      'Groß-/Kleinbuchstaben',
      'Zahlen und Sonderzeichen',
      'Stärke-Anzeige',
      'Mehrere Passwörter',
    ],
    faq: [
      { question: 'Wie sicher sind die Passwörter?', answer: 'Kryptografisch sicher mit Web Crypto API generiert.' },
    ],
    howTo: [
      'Stelle Länge und Optionen ein',
      'Klicke auf "Generieren"',
      'Kopiere das Passwort',
    ],
    relatedTools: ['hash-generator', 'uuid-generator'],
    isPopular: true,
  },
  {
    id: 'uuid-generator',
    slug: 'uuid-generieren',
    name: 'UUID Generator',
    shortName: 'UUID',
    description: 'Generiere UUIDs (Universally Unique Identifiers). Perfekt für IDs in Datenbanken und Anwendungen.',
    shortDescription: 'Erstelle eindeutige IDs',
    category: 'developer',
    keywords: ['uuid generator', 'guid', 'unique id', 'id generieren', 'uuid v4', 'identifier'],
    icon: 'Fingerprint',
    acceptsFiles: [],
    outputsFiles: ['text/plain'],
    features: [
      'UUID v1 (Zeitbasiert)',
      'UUID v4 (Random)',
      'Batch-Generierung',
      'Copy & Download',
    ],
    faq: [
      { question: 'Was ist der Unterschied zwischen v1 und v4?', answer: 'v1 ist zeitbasiert und sortierbar, v4 ist komplett zufällig.' },
    ],
    howTo: [
      'Wähle die UUID-Version',
      'Lege die Anzahl fest',
      'Generiere und kopiere',
    ],
    relatedTools: ['password-generator', 'hash-generator'],
  },

  // === CONVERTER TOOLS ===
  {
    id: 'unit-converter',
    slug: 'einheiten-umrechnen',
    name: 'Einheiten Umrechnen',
    shortName: 'Einheiten',
    description: 'Rechne zwischen verschiedenen Einheiten um: Länge, Gewicht, Temperatur, Volumen und mehr.',
    shortDescription: 'Konvertiere Maßeinheiten',
    category: 'converter',
    keywords: ['einheiten umrechnen', 'unit converter', 'länge umrechnen', 'gewicht umrechnen', 'temperatur umrechnen', 'meter in feet'],
    icon: 'Ruler',
    acceptsFiles: [],
    outputsFiles: ['text/plain'],
    features: [
      'Länge (m, km, mi, ft, in)',
      'Gewicht (kg, lb, oz)',
      'Temperatur (°C, °F, K)',
      'Volumen (l, gal, ml)',
      'Fläche (m², ha, acre)',
    ],
    faq: [
      { question: 'Welche Einheiten werden unterstützt?', answer: 'Länge, Gewicht, Temperatur, Volumen, Fläche, Zeit, Geschwindigkeit und mehr.' },
    ],
    howTo: [
      'Wähle die Kategorie',
      'Gib den Wert ein',
      'Sieh alle Umrechnungen',
    ],
    relatedTools: ['color-converter', 'number-base'],
    isPopular: true,
  },
  {
    id: 'color-converter',
    slug: 'farben-umrechnen',
    name: 'Farben Umrechnen',
    shortName: 'Farben',
    description: 'Konvertiere Farben zwischen HEX, RGB, HSL, CMYK und mehr. Mit Farbvorschau und Palette.',
    shortDescription: 'Wandle Farbformate um',
    category: 'converter',
    keywords: ['farbe umrechnen', 'color converter', 'hex zu rgb', 'rgb zu hex', 'farbcode', 'farbpalette'],
    icon: 'Palette',
    acceptsFiles: [],
    outputsFiles: ['text/plain'],
    features: [
      'HEX (#FFFFFF)',
      'RGB (255, 255, 255)',
      'HSL (0°, 0%, 100%)',
      'CMYK',
      'Farbvorschau',
      'Farbpalette',
    ],
    faq: [
      { question: 'Welche Farbformate werden unterstützt?', answer: 'HEX, RGB, RGBA, HSL, HSLA, CMYK und CSS-Namen.' },
    ],
    howTo: [
      'Gib eine Farbe ein',
      'Sieh alle Formate',
      'Kopiere das gewünschte Format',
    ],
    relatedTools: ['gradient-generator', 'unit-converter'],
  },
  {
    id: 'number-base',
    slug: 'zahlensystem-umrechnen',
    name: 'Zahlensystem Umrechnen',
    shortName: 'Zahlensystem',
    description: 'Konvertiere Zahlen zwischen Binär, Dezimal, Hexadezimal und Oktal. Mit Erklärungen.',
    shortDescription: 'Wandle zwischen Zahlensystemen um',
    category: 'converter',
    keywords: ['binär umrechnen', 'hexadezimal', 'dezimal', 'zahlensystem', 'binary converter', 'octal'],
    icon: 'Binary',
    acceptsFiles: [],
    outputsFiles: ['text/plain'],
    features: [
      'Binär (Base 2)',
      'Dezimal (Base 10)',
      'Hexadezimal (Base 16)',
      'Oktal (Base 8)',
      'Beliebige Base',
    ],
    faq: [
      { question: 'Kann ich auch andere Basen verwenden?', answer: 'Ja, du kannst jede Base von 2 bis 36 eingeben.' },
    ],
    howTo: [
      'Gib eine Zahl ein',
      'Wähle die Eingabe-Base',
      'Sieh alle Konvertierungen',
    ],
    relatedTools: ['unit-converter', 'base64-encoder'],
  },

  // === CALCULATOR TOOLS ===
  {
    id: 'percentage-calculator',
    slug: 'prozent-rechner',
    name: 'Prozent Rechner',
    shortName: 'Prozent',
    description: 'Berechne Prozente schnell und einfach. Prozent von Wert, Prozentuale Änderung, Aufschlag und mehr.',
    shortDescription: 'Berechne Prozente einfach',
    category: 'calculator',
    keywords: ['prozent rechner', 'percentage calculator', 'prozent berechnen', 'prozentuale änderung', 'prozent von'],
    icon: 'Percent',
    acceptsFiles: [],
    outputsFiles: ['text/plain'],
    features: [
      'X% von Y berechnen',
      'X ist Y% von was?',
      'Prozentuale Änderung',
      'Aufschlag/Abschlag',
      'MwSt. Berechnung',
    ],
    faq: [
      { question: 'Kann ich MwSt. berechnen?', answer: 'Ja, mit dem Aufschlag/Abschlag Rechner für 19% oder 7% MwSt.' },
    ],
    howTo: [
      'Wähle die Berechnungsart',
      'Gib die Werte ein',
      'Sieh das Ergebnis',
    ],
    relatedTools: ['unit-converter', 'date-calculator'],
    isPopular: true,
  },
  {
    id: 'date-calculator',
    slug: 'datumsrechner',
    name: 'Datumsrechner',
    shortName: 'Datum',
    description: 'Berechne Zeitabstände zwischen Daten, addiere Tage zu einem Datum oder finde Wochentage.',
    shortDescription: 'Berechne mit Daten und Zeiten',
    category: 'calculator',
    keywords: ['datumsrechner', 'date calculator', 'tage berechnen', 'datum differenz', 'wochentag', 'tage zählen'],
    icon: 'Calendar',
    acceptsFiles: [],
    outputsFiles: ['text/plain'],
    features: [
      'Tage zwischen Daten',
      'Datum + X Tage',
      'Wochentag finden',
      'Arbeitstage berechnen',
      'Alter berechnen',
    ],
    faq: [
      { question: 'Kann ich auch Arbeitstage berechnen?', answer: 'Ja, der Rechner kann Wochenenden und Feiertage ausschließen.' },
    ],
    howTo: [
      'Wähle die Berechnungsart',
      'Gib die Daten ein',
      'Sieh das Ergebnis',
    ],
    relatedTools: ['percentage-calculator', 'unit-converter'],
  },

  // === UTILITY TOOLS ===
  {
    id: 'qr-generator',
    slug: 'qr-code-erstellen',
    name: 'QR-Code Generator',
    shortName: 'QR-Code',
    description: 'Erstelle QR-Codes für URLs, Text, WiFi, vCards und mehr. Anpassbare Farben und Größe.',
    shortDescription: 'Generiere QR-Codes',
    category: 'utility',
    keywords: ['qr code', 'qr generator', 'qr erstellen', 'barcode', 'qr code erstellen', 'qr scanner'],
    icon: 'QrCode',
    acceptsFiles: [],
    outputsFiles: ['image/png', 'image/svg+xml'],
    features: [
      'URL-QR',
      'Text-QR',
      'WiFi-QR',
      'vCard-QR',
      'Farben anpassen',
      'SVG oder PNG Export',
    ],
    faq: [
      { question: 'Welche Inhalte kann ich kodieren?', answer: 'URLs, Text, WiFi-Zugangsdaten, Kontaktdaten (vCard), E-Mail und mehr.' },
    ],
    howTo: [
      'Wähle den QR-Typ',
      'Gib die Daten ein',
      'Passe das Design an',
      'Lade den QR-Code herunter',
    ],
    relatedTools: ['color-converter', 'password-generator'],
    isPopular: true,
  },
  {
    id: 'lorem-generator',
    slug: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    shortName: 'Lorem',
    description: 'Generiere Platzhaltertext für Designs und Mockups. Wörter, Sätze oder Absätze.',
    shortDescription: 'Erstelle Platzhaltertext',
    category: 'utility',
    keywords: ['lorem ipsum', 'platzhalter text', 'dummy text', 'blindtext', 'text generator'],
    icon: 'FileText',
    acceptsFiles: [],
    outputsFiles: ['text/plain'],
    features: [
      'Wörter',
      'Sätze',
      'Absätze',
      'Deutsche Option',
      'Start mit "Lorem ipsum..."',
    ],
    faq: [
      { question: 'Was ist Lorem Ipsum?', answer: 'Ein Platzhaltertext aus dem 16. Jahrhundert, der in der Typografie verwendet wird.' },
    ],
    howTo: [
      'Wähle die Einheit (Wörter/Sätze/Absätze)',
      'Lege die Anzahl fest',
      'Kopiere den generierten Text',
    ],
    relatedTools: ['text-counter', 'text-transform'],
  },
];

// Helper functions
export const getToolBySlug = (slug: string): ToolMetadata | undefined =>
  tools.find(t => t.slug === slug);

export const getToolById = (id: string): ToolMetadata | undefined =>
  tools.find(t => t.id === id);

export const getToolsByCategory = (category: string): ToolMetadata[] =>
  tools.filter(t => t.category === category);

export const getPopularTools = (): ToolMetadata[] =>
  tools.filter(t => t.isPopular);

export const getNewTools = (): ToolMetadata[] =>
  tools.filter(t => t.isNew);

export const searchTools = (query: string): ToolMetadata[] => {
  const q = query.toLowerCase().trim();
  if (!q) return tools;
  
  return tools.filter(t => 
    t.name.toLowerCase().includes(q) ||
    t.shortName.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.keywords.some(k => k.toLowerCase().includes(q))
  ).sort((a, b) => {
    // Prioritize name matches
    const aName = a.name.toLowerCase().includes(q) ? 0 : 1;
    const bName = b.name.toLowerCase().includes(q) ? 0 : 1;
    return aName - bName;
  });
};

export const getAllKeywords = (): string[] => {
  const keywordSet = new Set<string>();
  tools.forEach(t => t.keywords.forEach(k => keywordSet.add(k)));
  return Array.from(keywordSet);
};
